# Generated by Django 5.0.6 on 2024-09-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('soft_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('soft_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('soft_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncoTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('soft_delete', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_email', models.EmailField(max_length=80)),
                ('sales_represent', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('cust_name', 'cust_email', 'sales_represent', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='VersionedRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
                ('soft_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.company')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.destination')),
                ('freight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.freighttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.source')),
                ('transit_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.transittime')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('soft_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.company')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.destination')),
                ('freight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.freighttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.source')),
                ('transit_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.transittime')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='aggregator.versionedrate')),
            ],
            options={
                'unique_together': {('company', 'source', 'destination', 'transit_time', 'freight_type', 'effective_date', 'expiration_date', 'soft_delete')},
            },
        ),
        migrations.CreateModel(
            name='ManualRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('cargotype', models.CharField(max_length=50)),
                ('direct_shipment', models.BooleanField(blank=True, default=False, null=True)),
                ('transhipment_add_port', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('terms_condition', models.CharField(blank=True, null=True)),
                ('soft_delete', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.company')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.destination')),
                ('freight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.freighttype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.source')),
                ('transit_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregator.transittime')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manualrates', to='aggregator.versionedrate')),
            ],
            options={
                'unique_together': {('company', 'destination', 'source', 'direct_shipment', 'transhipment_add_port', 'cargotype', 'transit_time', 'freight_type', 'rate', 'effective_date', 'expiration_date', 'remarks', 'terms_condition', 'soft_delete', 'version')},
            },
        ),
    ]
