# Generated by Django 5.0.6 on 2024-10-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='unique_uuid',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='versionedrate',
            name='unique_uuid',
            field=models.CharField(editable=False, max_length=12, null=True, unique=True),
        ),
    ]
