# Generated by Django 5.0.6 on 2024-10-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manualrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='manualrate',
            name='free_days_comment',
            field=models.CharField(default='testing', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='manualrate',
            name='hazardous',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='manualrate',
            name='un_number',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='manualrate',
            unique_together={('company', 'destination', 'source', 'direct_shipment', 'spot_filed', 'free_days', 'free_days_comment', 'hazardous', 'un_number', 'transhipment_add_port', 'cargotype', 'transit_time', 'freight_type', 'rate', 'currency', 'effective_date', 'expiration_date', 'remarks', 'terms_condition', 'soft_delete', 'version')},
        ),
    ]
