# Generated by Django 5.0.6 on 2024-11-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerinfo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='customerinfo',
            unique_together={('company_name', 'cust_name', 'cust_email', 'sales_represent', 'phone', 'percentage', 'terms_condition')},
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('action_type', models.CharField(max_length=150)),
                ('action_status', models.BooleanField(null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.destination')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.source')),
            ],
        ),
    ]
