# Generated by Django 5.0.6 on 2025-01-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_clientinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='client_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
