# Generated by Django 5.0.6 on 2025-01-13 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_alter_clientinfo_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='activityLog', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='clienttemplatecompany',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='clientTemplateCompany', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='comodity',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='comodity', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='company',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='company', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='customerInfo', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='destination',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='freighttype',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='freightType', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='incoterm',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='incoTerm', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='manualrate',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='manualRates', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='rate',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='source',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='source', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='transittime',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='transitTime', to='aggregator.clientinfo'),
        ),
        migrations.AddField(
            model_name='versionedrate',
            name='client',
            field=models.ForeignKey(default='Grace_20250107173155', on_delete=django.db.models.deletion.CASCADE, related_name='versionedRate', to='aggregator.clientinfo'),
        ),
    ]
