# Generated by Django 5.0.6 on 2024-10-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_alter_rate_unique_together_rate_free_days_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rate',
            name='currency',
            field=models.CharField(default='USD', max_length=15),
        ),
        migrations.AddField(
            model_name='versionedrate',
            name='currency',
            field=models.CharField(default='USD', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('company', 'source', 'destination', 'transit_time', 'freight_type', 'currency', 'spot_filed', 'free_days', 'free_days_comment', 'hazardous', 'un_number', 'effective_date', 'expiration_date', 'soft_delete')},
        ),
    ]
