# Generated by Django 5.1.1 on 2024-10-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_alter_rate_unique_uuid_and_more'),
        ('aggregator', '0004_alter_rate_unique_together_rate_currency_and_more'),
    ]

    operations = [
    ]
