# Generated by Django 5.0.6 on 2025-01-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_activitylog_client_clienttemplatecompany_client_and_more'),
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, default='Grace_20250107173155', null=True, on_delete=django.db.models.deletion.CASCADE, to='aggregator.clientinfo'),
        ),
    ]
